//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTExtractXMLMeterDatatoCSV {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTExtractXMLMeterDatatoCSV.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ase:aseXML xmlns:ase=&quot;urn:aseXML:r32&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;urn:aseXML:r32 http://www.nemmco.com.au/aseXML/schemas/r32/aseXML_r32.xsd&quot;&gt;
        ///	&lt;Header&gt;
        ///		&lt;From&gt;GENMP&lt;/From&gt;
        ///		&lt;To&gt;GENRTL&lt;/To&gt;
        ///		&lt;MessageID&gt;HGL_161007_133124&lt;/MessageID&gt;
        ///		&lt;MessageDate&gt;2018-01-20T10:10:22+10:00&lt;/MessageDate&gt;
        ///		&lt;TransactionGroup&gt;MTRD&lt;/TransactionGroup&gt;
        ///		&lt;Priority&gt;Low&lt;/Priority&gt;
        ///		&lt;Market&gt;NEM&lt;/Market&gt;
        ///	&lt;/Header&gt;
        ///	&lt;Transactions&gt;
        ///		&lt;Transaction transactionDate=&quot;2018-01-01T10:10:22+10: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CleanTestFile {
            get {
                return ResourceManager.GetString("CleanTestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ase:aseXML xmlns:ase=&quot;urn:aseXML:r32&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;urn:aseXML:r32 http://www.nemmco.com.au/aseXML/schemas/r32/aseXML_r32.xsd&quot;&gt;
        ///	&lt;Header&gt;
        ///		&lt;From&gt;GENMP&lt;/From&gt;
        ///		&lt;To&gt;GENRTL&lt;/To&gt;
        ///		&lt;MessageID&gt;HGL_161007_133124&lt;/MessageID&gt;
        ///		&lt;MessageDate&gt;2018-01-20T10:10:22+10:00&lt;/MessageDate&gt;
        ///		&lt;TransactionGroup&gt;MTRD&lt;/TransactionGroup&gt;
        ///		&lt;Priority&gt;Low&lt;/Priority&gt;
        ///		&lt;Market&gt;NEM&lt;/Market&gt;
        ///	&lt;/Header&gt;
        ///	&lt;Transactions&gt;
        ///		&lt;Transaction transactionDate=&quot;2018-01-01T10:10:22+10: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string header_morethanone {
            get {
                return ResourceManager.GetString("header_morethanone", resourceCulture);
            }
        }
    }
}
